# Generated by Django 5.1.4 on 2025-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_alter_board_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
