# Generated by Django 5.1.4 on 2025-02-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_board_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='workspace',
            new_name='workspace_id',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='assignee',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='workspace',
            new_name='workspace_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='task_list_id',
        ),
        migrations.RenameField(
            model_name='taskassignee',
            old_name='assignee',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='taskassignee',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='tasklabel',
            old_name='label',
            new_name='label_id',
        ),
        migrations.RenameField(
            model_name='tasklabel',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='board',
            new_name='board_id',
        ),
    ]
