# Generated by Django 5.1.4 on 2025-02-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_rename_workspace_board_workspace_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='workspacemember',
            old_name='member',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='workspacemember',
            old_name='workspace',
            new_name='workspace_id',
        ),
    ]
