# Generated by Django 5.1.4 on 2025-03-26 18:03

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
			('project_management', '0005_rename_owner_workspace_owner_id_and_more'),
	]

	operations = [
			migrations.RenameField(
				model_name='board',
				old_name='workspace_id',
				new_name='workspace',
			),
			migrations.RenameField(
				model_name='checklistitem',
				old_name='assignee_id',
				new_name='assignee',
			),
			migrations.RenameField(
				model_name='checklistitem',
				old_name='task_id',
				new_name='task',
			),
			migrations.RenameField(
				model_name='invite',
				old_name='sender_id',
				new_name='sender',
			),
			migrations.RenameField(
				model_name='invite',
				old_name='workspace_id',
				new_name='workspace',
			),
			migrations.RenameField(
				model_name='task',
				old_name='task_list_id',
				new_name='task_list',
			),
			migrations.RenameField(
				model_name='taskassignee',
				old_name='assignee_id',
				new_name='assignee',
			),
			migrations.RenameField(
				model_name='taskassignee',
				old_name='task_id',
				new_name='task',
			),
			migrations.RenameField(
				model_name='tasklabel',
				old_name='label_id',
				new_name='label',
			),
			migrations.RenameField(
				model_name='tasklabel',
				old_name='task_id',
				new_name='task',
			),
			migrations.RenameField(
				model_name='tasklist',
				old_name='board_id',
				new_name='board',
			),
			migrations.RenameField(
				model_name='workspace',
				old_name='owner_id',
				new_name='owner',
			),
			migrations.RenameField(
				model_name='workspacemember',
				old_name='member_id',
				new_name='member',
			),
			migrations.RenameField(
				model_name='workspacemember',
				old_name='workspace_id',
				new_name='workspace',
			),
	]
