# Generated by Django 5.1.4 on 2025-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
			('project_management', '0006_rename_workspace_id_board_workspace_and_more'),
	]

	operations = [
			migrations.AddField(
				model_name='board',
				name='slug',
				field=models.CharField(blank=True, default='<django.db.models.fields.CharField>', max_length=255),
			),
			migrations.AddField(
				model_name='workspace',
				name='slug',
				field=models.CharField(blank=True, max_length=255),
			),
			migrations.AlterField(
				model_name='board',
				name='description',
				field=models.TextField(blank=True, null=True),
			),
			migrations.AlterUniqueTogether(
				name='board',
				unique_together={('workspace', 'position'), ('workspace', 'slug')},
			),
	]
