# Generated by Django 5.1.4 on 2025-03-27 07:02

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
			('project_management', '0007_board_slug_workspace_slug_alter_board_description_and_more'),
	]

	operations = [
			migrations.AlterUniqueTogether(
				name='board',
				unique_together={('workspace', 'name'), ('workspace', 'position')},
			),
	]
