# Generated by Django 5.1.4 on 2025-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_management",
            "0009_alter_board_slug_boardinvite_boardmember_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
